### ISSUE TITLE
asciinema link broken

### ISSUE THREAD

**Issue by maglub** [ozzi-/microblog#1]
Hello!

Nice little project. The asciinema link https://asciinema.org/a/fk6GCh7YaCtUagTrRy2PgkM3G is broken.

Have a nice day!

**Comment by ozzi-** [comment]
Hi maglub
Thanks for pointing out the broken link, I created a new one.
Cheers

https://asciinema.org/a/yNyRUz6pDMRGsOBh2SSCwaDne
